services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fastifi_api_network

volumes:
  mongodb_data:
networks:
  fastifi_api_network:
