version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - fastifi_api_network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    env_file:
      - .env
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - fastifi_api_network

  email-service:
    container_name: email-service
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    command: ./wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run service:email
    environment:
      NODE_ENV: development
    depends_on:
      - rabbitmq
    volumes:
      - .:/app
      - ./.env:/app/.env
    networks:
      - fastifi_api_network


  app:
    container_name: app
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
      - ./.env:/app/.env
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    command: ./wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run start
    environment:
      NODE_ENV: development
    depends_on:
      - mongodb
      - rabbitmq
      - email-service
    networks:
      - fastifi_api_network
volumes:
  mongodb_data:
networks:
  fastifi_api_network:
